CREATE TABLE analiz (
    id_analiz integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_group boolean NULL,
    material_type integer NULL,
    code_name varchar(50) NULL,
    full_name varchar(255) NULL,
    id_ill integer NULL,
    text_norm varchar(255) NULL,
    price numeric(8, 2) NULL,
    normtext varchar(2048) NULL,
    unnormtext varchar(2048) NULL,
    CONSTRAINT analiz_pkey PRIMARY KEY (id_analiz)
);

CREATE TABLE employee (
    id_employee integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login_name varchar(50) NOT NULL,
    name varchar(50) NOT NULL,
    patronymic varchar(50) NOT NULL,
    surname varchar(50) NOT NULL,
    email varchar(50) NULL,
    post varchar(50) NULL,
    createdate timestamp NULL,
    updatedate timestamp NULL,
    erasedate timestamp NULL,
    archived boolean NOT NULL,
    is_role boolean NOT NULL,
    role integer NULL,
    full_name varchar(101) GENERATED ALWAYS AS ((surname || ' ') || name) STORED,
    CONSTRAINT employee_pkey PRIMARY KEY (id_employee)
);

CREATE TABLE organization (
    id_organization integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    org_name varchar(255) NULL,
    template_fn varchar(255) NULL,
    id_printtemplate integer NULL,
    email varchar(255) NULL,
    secondemail varchar(255) NULL,
    fax varchar(255) NULL,
    secondfax varchar(255) NULL,
    CONSTRAINT organization_pkey PRIMARY KEY (id_organization)
);

CREATE TABLE printtemplate (
    id_printtemplate integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    templatename varchar(255) NULL,
    createdate timestamp NULL,
    ext varchar(10) NULL,
    comment varchar(255) NULL,
    templatebody bytea NULL,
    id_templatetype integer NULL,
    CONSTRAINT printtemplate_pkey PRIMARY KEY (id_printtemplate)
);

CREATE TABLE selecttype (
    id_selecttype integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    selecttype varchar(50) NULL,
    CONSTRAINT selecttype_pkey PRIMARY KEY (id_selecttype)
);

CREATE TABLE templatetype (
    id_templatetype integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    temlateval varchar(50) NULL,
    comment varchar(255) NULL,
    CONSTRAINT templatetype_pkey PRIMARY KEY (id_templatetype)
);

CREATE TABLE workitem (
    id_workitem integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_date timestamp NULL,
    is_complit boolean NOT NULL,
    close_date timestamp NULL,
    id_employee integer NULL,
    id_analiz integer NULL,
    id_work integer NULL,
    is_print boolean NOT NULL,
    is_select boolean NOT NULL,
    is_normtextprint boolean NULL,
    price numeric(8, 2) NULL,
    id_selecttype integer NULL,
    CONSTRAINT workitem_pkey PRIMARY KEY (id_workitem)
);

CREATE TABLE works (
    id_work integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_complit boolean NOT NULL,
    create_date timestamp NULL,
    close_date timestamp NULL,
    id_employee integer NULL,
    id_organization integer NULL,
    comment varchar(255) NULL,
    print_date timestamp NULL,
    org_name varchar(50) NULL,
    part_name varchar(50) NULL,
    org_regn integer NULL,
    material_type smallint NULL,
    material_get_date timestamp NULL,
    material_reg_date timestamp NULL,
    materialnumber numeric(8, 2) NULL,
    material_comment varchar(255) NULL,
    fio varchar(255) NOT NULL,
    phone varchar(50) NULL,
    email varchar(255) NULL,
    is_del boolean NOT NULL,
    id_employee_del integer NULL,
    deldate timestamp NULL,
    price numeric(8, 2) NULL,
    extregn varchar(255) NULL,
    medicalhistorynumber varchar(255) NULL,
    doctorfio varchar(255) NULL,
    doctorphone varchar(255) NULL,
    organizationfax varchar(255) NULL,
    organizationemail varchar(255) NULL,
    doctoremail varchar(255) NULL,
    statusid smallint NULL,
    sendtoorgdate timestamp NULL,
    sendtoclientdate timestamp NULL,
    sendtodoctordate timestamp NULL,
    sendtofax timestamp NULL,
    sendtoapp timestamp NULL,
    CONSTRAINT works_pkey PRIMARY KEY (id_work)
);

CREATE TABLE workstatus (
    statusid smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    statusname varchar(255) NULL,
    CONSTRAINT pk_workstatus PRIMARY KEY (statusid)
);

CREATE UNIQUE INDEX xakloginname ON employee (login_name);
CREATE INDEX xif1organization ON organization (id_printtemplate);
CREATE INDEX xif1printtemplate ON printtemplate (id_templatetype);
CREATE INDEX xif3workitem ON workitem (id_employee);
CREATE INDEX xif4workitem ON workitem (id_analiz);
CREATE INDEX xif5workitem ON workitem (id_work);
CREATE INDEX xif6workitem ON workitem (id_selecttype);
CREATE INDEX xif1works ON works (id_employee);
CREATE INDEX xif2works ON works (id_organization);
CREATE INDEX xif3works ON works (id_employee_del);

ALTER TABLE employee ALTER COLUMN login_name SET DEFAULT current_user;
ALTER TABLE employee ALTER COLUMN name SET DEFAULT '';
ALTER TABLE employee ALTER COLUMN patronymic SET DEFAULT '';
ALTER TABLE employee ALTER COLUMN surname SET DEFAULT '';
ALTER TABLE employee ALTER COLUMN archived SET DEFAULT false;
ALTER TABLE employee ALTER COLUMN is_role SET DEFAULT false;
ALTER TABLE employee ALTER COLUMN role SET DEFAULT 0;
ALTER TABLE printtemplate ALTER COLUMN createdate SET DEFAULT now();
ALTER TABLE workitem ALTER COLUMN create_date SET DEFAULT now();
ALTER TABLE workitem ALTER COLUMN is_complit SET DEFAULT false;
ALTER TABLE workitem ALTER COLUMN is_print SET DEFAULT true;
ALTER TABLE workitem ALTER COLUMN is_select SET DEFAULT false;
ALTER TABLE workitem ALTER COLUMN is_normtextprint SET DEFAULT true;
ALTER TABLE works ALTER COLUMN is_complit SET DEFAULT false;
ALTER TABLE works ALTER COLUMN create_date SET DEFAULT now();
ALTER TABLE works ALTER COLUMN material_get_date SET DEFAULT now();
ALTER TABLE works ALTER COLUMN material_reg_date SET DEFAULT now();
ALTER TABLE works ALTER COLUMN is_del SET DEFAULT false;

ALTER TABLE organization
    ADD CONSTRAINT fk__organizat__id_pr__14270015
    FOREIGN KEY (id_printtemplate)
    REFERENCES printtemplate (id_printtemplate);

ALTER TABLE printtemplate
    ADD CONSTRAINT fk__printtemp__id_te__151b244e
    FOREIGN KEY (id_templatetype)
    REFERENCES templatetype (id_templatetype);

ALTER TABLE workitem
    ADD CONSTRAINT fk__workitem__id_ana__1f98b2c1
    FOREIGN KEY (id_analiz)
    REFERENCES analiz (id_analiz);

ALTER TABLE workitem
    ADD CONSTRAINT fk__workitem__id_emp__208cd6fa
    FOREIGN KEY (id_employee)
    REFERENCES employee (id_employee);

ALTER TABLE workitem
    ADD CONSTRAINT fk__workitem__id_sel__1db06a4f
    FOREIGN KEY (id_selecttype)
    REFERENCES selecttype (id_selecttype);

ALTER TABLE workitem
    ADD CONSTRAINT fk__workitem__id_wor__1ea48e88
    FOREIGN KEY (id_work)
    REFERENCES works (id_work)
    ON DELETE CASCADE;

ALTER TABLE works
    ADD CONSTRAINT fk__works__id_employ__2180fb33
    FOREIGN KEY (id_employee_del)
    REFERENCES employee (id_employee);

ALTER TABLE works
    ADD CONSTRAINT fk__works__id_employ__236943a5
    FOREIGN KEY (id_employee)
    REFERENCES employee (id_employee);

ALTER TABLE works
    ADD CONSTRAINT fk__works__id_organi__22751f6c
    FOREIGN KEY (id_organization)
    REFERENCES organization (id_organization);

CREATE OR REPLACE FUNCTION f_employee_get()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    result integer;
BEGIN
    SELECT e.id_employee
    INTO result
    FROM employee e
    WHERE e.login_name = current_user;

    RETURN result;
END;
$$;

CREATE OR REPLACE FUNCTION f_employee_fullname(p_id_employee integer)
RETURNS varchar(101)
LANGUAGE plpgsql
AS $$
DECLARE
    result varchar(101);
BEGIN
    p_id_employee := coalesce(p_id_employee, f_employee_get());

    IF p_id_employee = -1 THEN
        result := '';
    ELSE
        SELECT e.surname || ' ' || upper(substring(e.name from 1 for 1)) || '. ' ||
               upper(substring(e.patronymic from 1 for 1)) || '.'
        INTO result
        FROM employee e
        WHERE e.id_employee = p_id_employee;
    END IF;

    result := rtrim(replace(result, '. .', ''));

    IF result = '' THEN
        SELECT e.login_name
        INTO result
        FROM employee e
        WHERE e.id_employee = p_id_employee;
    END IF;

    RETURN result;
END;
$$;

CREATE OR REPLACE FUNCTION f_workitems_count_by_id_work(
    p_id_work integer,
    p_is_complit boolean
)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    result integer;
BEGIN
    SELECT count(*)::integer
    INTO result
    FROM workitem
    WHERE id_work = p_id_work
      AND id_analiz NOT IN (
          SELECT id_analiz
          FROM analiz
          WHERE is_group = true
      )
      AND is_complit = p_is_complit;

    RETURN result;
END;
$$;

CREATE OR REPLACE FUNCTION f_works_list()
RETURNS TABLE
(
    id_work integer,
    create_date timestamp,
    materialnumber numeric(8, 2),
    is_complit boolean,
    fio varchar(255),
    d_date varchar(10),
    workitemsnotcomplit integer,
    workitemscomplit integer,
    full_name varchar(101),
    statusid smallint,
    statusname varchar(255),
    is_print boolean
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        w.id_work,
        w.create_date,
        w.materialnumber,
        w.is_complit,
        w.fio,
        to_char(w.create_date, 'DD.MM.YYYY')::varchar(10) AS d_date,
        f_workitems_count_by_id_work(w.id_work, false) AS workitemsnotcomplit,
        f_workitems_count_by_id_work(w.id_work, true) AS workitemscomplit,
        f_employee_fullname(w.id_employee) AS full_name,
        w.statusid,
        ws.statusname,
        CASE
            WHEN w.print_date IS NOT NULL OR
                 w.sendtoclientdate IS NOT NULL OR
                 w.sendtodoctordate IS NOT NULL OR
                 w.sendtoorgdate IS NOT NULL OR
                 w.sendtofax IS NOT NULL
            THEN true
            ELSE false
        END AS is_print
    FROM works w
    LEFT JOIN workstatus ws ON w.statusid = ws.statusid
    WHERE w.is_del <> true
    ORDER BY w.id_work DESC;
END;
$$;
