/*
    Полная PostgreSQL-версия исходного скрипта MS SQL Server.

    Что сохранено:
    - все основные таблицы из исходного скрипта;
    - индексы;
    - значения по умолчанию через ALTER TABLE;
    - внешние ключи через ALTER TABLE;
    - все функции присутствуют.

    Что изменено:
    - синтаксис MS SQL Server переведен на синтаксис PostgreSQL;
    - bit -> boolean;
    - datetime -> timestamp;
    - image -> bytea;
    - identity(1,1) -> generated by default as identity;
    - SYSTEM_USER / suser_sname() -> current_user;
    - dbo.F_WORKITEMS_COUNT_BY_ID_WORK(id_work, is_complit) оптимизирована:
      теперь она принимает массив идентификаторов заказов и возвращает счетчики
      для всех этих заказов одним наборным запросом с GROUP BY;
    - F_WORKS_LIST использует эту функцию один раз, а не два раза на каждую строку.

    Проблемный фрагмент в исходном MS SQL Server-скрипте:

        dbo.F_WORKITEMS_COUNT_BY_ID_WORK(works.Id_Work,0) as WorkItemsNotComplit,
        dbo.F_WORKITEMS_COUNT_BY_ID_WORK(works.Id_Work,1) as WorkItemsComplit,

    Оптимизированный вариант в PostgreSQL:

        work_ids as (
            select array_agg(tw.id_work) as ids
            from top_works tw
        ),
        workitem_counts as (
            select c.*
            from work_ids ids
            cross join f_workitems_count_by_id_work(ids.ids) c
        )

    Количество вызовов функции меняется с:

        3000 * 2 = 6000 вызовов

    на:

        1 вызов
*/

-- ============================================================
-- Необязательная очистка для повторного запуска.
-- Раскомментируй, если нужно пересоздать объекты с нуля.
-- ============================================================

/*
drop function if exists f_works_list();
drop function if exists f_workitems_count_by_id_work(integer[]);
drop function if exists f_workitems_count_by_id_work(integer, boolean);
drop function if exists f_employee_fullname(integer);
drop function if exists f_employee_get();

drop table if exists workitem cascade;
drop table if exists works cascade;
drop table if exists organization cascade;
drop table if exists printtemplate cascade;
drop table if exists templatetype cascade;
drop table if exists selecttype cascade;
drop table if exists employee cascade;
drop table if exists analiz cascade;
drop table if exists workstatus cascade;
*/

-- ============================================================
-- Таблицы
-- ============================================================

create table analiz
(
    id_analiz integer generated by default as identity not null,
    is_group boolean null,
    material_type integer null,
    code_name varchar(50) null,
    full_name varchar(255) null,
    id_ill integer null,
    text_norm varchar(255) null,
    price numeric(8, 2) null,
    normtext varchar(2048) null,
    unnormtext varchar(2048) null,
    constraint analiz_pkey primary key (id_analiz)
);

create table employee
(
    id_employee integer generated by default as identity not null,
    login_name varchar(50) not null,
    name varchar(50) not null,
    patronymic varchar(50) not null,
    surname varchar(50) not null,
    email varchar(50) null,
    post varchar(50) null,
    createdate timestamp null,
    updatedate timestamp null,
    erasedate timestamp null,
    archived boolean not null,
    is_role boolean not null,
    role integer null,
    full_name varchar(101) generated always as ((surname || ' ' || name)) stored,
    constraint employee_pkey primary key (id_employee)
);

create table organization
(
    id_organization integer generated by default as identity not null,
    org_name varchar(255) null,
    template_fn varchar(255) null,
    id_printtemplate integer null,
    email varchar(255) null,
    secondemail varchar(255) null,
    fax varchar(255) null,
    secondfax varchar(255) null,
    constraint organization_pkey primary key (id_organization)
);

create table printtemplate
(
    id_printtemplate integer generated by default as identity not null,
    templatename varchar(255) null,
    createdate timestamp null,
    ext varchar(10) null,
    comment varchar(255) null,
    templatebody bytea null,
    id_templatetype integer null,
    constraint printtemplate_pkey primary key (id_printtemplate)
);

create table selecttype
(
    id_selecttype integer generated by default as identity not null,
    selecttype varchar(50) null,
    constraint selecttype_pkey primary key (id_selecttype)
);

create table templatetype
(
    id_templatetype integer generated by default as identity not null,
    temlateval varchar(50) null,
    comment varchar(255) null,
    constraint templatetype_pkey primary key (id_templatetype)
);

create table works
(
    id_work integer generated by default as identity not null,
    is_complit boolean not null,
    create_date timestamp null,
    close_date timestamp null,
    id_employee integer null,
    id_organization integer null,
    comment varchar(255) null,
    print_date timestamp null,
    org_name varchar(50) null,
    part_name varchar(50) null,
    org_regn integer null,
    material_type smallint null,
    material_get_date timestamp null,
    material_reg_date timestamp null,
    materialnumber numeric(8, 2) null,
    material_comment varchar(255) null,
    fio varchar(255) not null,
    phone varchar(50) null,
    email varchar(255) null,
    is_del boolean not null,
    id_employee_del integer null,
    deldate timestamp null,
    price numeric(8, 2) null,
    extregn varchar(255) null,
    medicalhistorynumber varchar(255) null,
    doctorfio varchar(255) null,
    doctorphone varchar(255) null,
    organizationfax varchar(255) null,
    organizationemail varchar(255) null,
    doctoremail varchar(255) null,
    statusid smallint null,
    sendtoorgdate timestamp null,
    sendtoclientdate timestamp null,
    sendtodoctordate timestamp null,
    sendtofax timestamp null,
    sendtoapp timestamp null,
    constraint works_pkey primary key (id_work)
);

create table workstatus
(
    statusid smallint generated by default as identity not null,
    statusname varchar(255) null,
    constraint pk_workstatus primary key (statusid)
);

create table workitem
(
    id_workitem integer generated by default as identity not null,
    create_date timestamp null,
    is_complit boolean not null,
    close_date timestamp null,
    id_employee integer null,
    id_analiz integer null,
    id_work integer null,
    is_print boolean not null,
    is_select boolean not null,
    is_normtextprint boolean null,
    price numeric(8, 2) null,
    id_selecttype integer null,
    constraint workitem_pkey primary key (id_workitem)
);

-- ============================================================
-- Индексы
-- ============================================================

create unique index xakloginname on employee (login_name);

create index xif1organization on organization (id_printtemplate);

create index xif1printtemplate on printtemplate (id_templatetype);

create index xif3workitem on workitem (id_employee);

create index xif4workitem on workitem (id_analiz);

create index xif5workitem on workitem (id_work);

create index xif6workitem on workitem (id_selecttype);

create index xif1works on works (id_employee);

create index xif2works on works (id_organization);

create index xif3works on works (id_employee_del);

-- Полезный индекс для оптимизированной функции списка заказов.
-- В исходном скрипте был только xif5workitem на workitem(id_work).
-- Этот индекс ускоряет подсчет по id_work и is_complit.
create index if not exists ix_workitem_id_work_is_complit
    on workitem (id_work, is_complit)
    where id_analiz is not null;

-- Полезный индекс для order by id_work desc с фильтром is_del.
create index if not exists ix_works_active_id_work_desc
    on works (id_work desc)
    where is_del = false;

-- ============================================================
-- Значения по умолчанию
-- ============================================================

alter table employee alter column login_name set default current_user;
alter table employee alter column name set default '';
alter table employee alter column patronymic set default '';
alter table employee alter column surname set default '';
alter table employee alter column archived set default false;
alter table employee alter column is_role set default false;
alter table employee alter column role set default 0;

alter table printtemplate alter column createdate set default now();

alter table workitem alter column create_date set default now();
alter table workitem alter column is_complit set default false;
alter table workitem alter column is_print set default true;
alter table workitem alter column is_select set default false;
alter table workitem alter column is_normtextprint set default true;

alter table works alter column is_complit set default false;
alter table works alter column create_date set default now();
alter table works alter column material_get_date set default now();
alter table works alter column material_reg_date set default now();
alter table works alter column is_del set default false;

-- ============================================================
-- Внешние ключи
-- ============================================================

alter table organization
    add constraint fk_organization_id_printtemplate
    foreign key (id_printtemplate)
    references printtemplate (id_printtemplate);

alter table printtemplate
    add constraint fk_printtemplate_id_templatetype
    foreign key (id_templatetype)
    references templatetype (id_templatetype);

alter table workitem
    add constraint fk_workitem_id_analiz
    foreign key (id_analiz)
    references analiz (id_analiz);

alter table workitem
    add constraint fk_workitem_id_employee
    foreign key (id_employee)
    references employee (id_employee);

alter table workitem
    add constraint fk_workitem_id_selecttype
    foreign key (id_selecttype)
    references selecttype (id_selecttype);

alter table workitem
    add constraint fk_workitem_id_work
    foreign key (id_work)
    references works (id_work)
    on delete cascade;

alter table works
    add constraint fk_works_id_employee_del
    foreign key (id_employee_del)
    references employee (id_employee);

alter table works
    add constraint fk_works_id_employee
    foreign key (id_employee)
    references employee (id_employee);

alter table works
    add constraint fk_works_id_organization
    foreign key (id_organization)
    references organization (id_organization);

-- ============================================================
-- Функции
-- ============================================================

drop function if exists f_works_list();
drop function if exists f_workitems_count_by_id_work(integer[]);
drop function if exists f_workitems_count_by_id_work(integer, boolean);
drop function if exists f_employee_fullname(integer);
drop function if exists f_employee_get();

-- ------------------------------------------------------------
-- Исходная идея из SQL Server:
--
-- F_EMPLOYEE_GET()
-- возвращает идентификатор текущего сотрудника,
-- сравнивая Employee.Login_Name с SYSTEM_USER.
--
-- Версия для PostgreSQL:
-- SYSTEM_USER / suser_sname() -> current_user.
-- ------------------------------------------------------------

create or replace function f_employee_get()
returns integer
language sql
stable
as $$
    select e.id_employee
    from employee e
    where e.login_name = current_user
    limit 1;
$$;

-- ------------------------------------------------------------
-- Исходная идея из SQL Server:
--
-- F_EMPLOYEE_FULLNAME(@ID_EMPLOYEE)
-- если id равен null, использовать F_EMPLOYEE_GET();
-- если id = -1, вернуть пустую строку;
-- иначе вернуть строку вида 'Фамилия И. О.';
-- если результат пустой, вернуть Login_Name.
-- ------------------------------------------------------------

create or replace function f_employee_fullname(p_id_employee integer)
returns varchar(101)
language sql
stable
as $$
    with employee_id as (
        select coalesce(p_id_employee, f_employee_get()) as id_employee
    )
    select
        cast(
            case
                when employee_id.id_employee = -1 then ''
                else
                    coalesce(
                        nullif(
                            rtrim(
                                replace(
                                    e.surname || ' ' ||
                                    upper(substr(e.name, 1, 1)) || '. ' ||
                                    upper(substr(e.patronymic, 1, 1)) || '.',
                                    '. .',
                                    ''
                                )
                            ),
                            ''
                        ),
                        e.login_name,
                        ''
                    )
            end
        as varchar(101))
    from employee_id
    left join employee e
        on e.id_employee = employee_id.id_employee;
$$;

-- ------------------------------------------------------------
-- Исходная функция SQL Server:
--
-- F_WORKITEMS_COUNT_BY_ID_WORK(@id_work, @is_complit)
-- возвращала одно число для одного заказа и одного признака завершенности.
--
-- Проблема:
-- F_WORKS_LIST вызывала ее два раза на каждую строку:
--
--     F_WORKITEMS_COUNT_BY_ID_WORK(works.Id_Work, 0)
--     F_WORKITEMS_COUNT_BY_ID_WORK(works.Id_Work, 1)
--
-- Для 3000 заказов это 6000 вызовов функции.
--
-- Оптимизированная версия для PostgreSQL:
-- один вызов принимает integer[] и возвращает оба счетчика для всех заказов.
-- ------------------------------------------------------------

create or replace function f_workitems_count_by_id_work(
    p_work_ids integer[]
)
returns table
(
    id_work integer,
    workitemsnotcomplit integer,
    workitemscomplit integer
)
language sql
stable
as $$
    select
        wi.id_work,

        count(*) filter (
            where wi.is_complit = false
        )::integer as workitemsnotcomplit,

        count(*) filter (
            where wi.is_complit = true
        )::integer as workitemscomplit

    from workitem wi
    where wi.id_work = any(p_work_ids)
      and wi.id_analiz is not null
      and not exists (
          select 1
          from analiz a
          where a.id_analiz = wi.id_analiz
            and a.is_group = true
      )
    group by wi.id_work;
$$;

-- ------------------------------------------------------------
-- Исходная функция SQL Server:
--
-- F_WORKS_LIST() была многооператорной табличной функцией:
-- она вставляла строки во внутреннюю табличную переменную и вызывала
-- F_WORKITEMS_COUNT_BY_ID_WORK два раза для каждой строки Works.
--
-- Оптимизированная версия для PostgreSQL:
-- 1. сначала берем только последние 3000 заказов;
-- 2. считаем элементы заказов одним вызовом функции;
-- 3. присоединяем счетчики обратно к заказам.
--
-- Клиентский запрос:
--     select *
--     from f_works_list()
--     limit 3000;
--
-- Функция сама ограничивает результат 3000 строками, потому что исходный
-- клиентский запрос не всегда может надежно протолкнуть LIMIT внутрь процедурной функции.
-- ------------------------------------------------------------

create or replace function f_works_list()
returns table
(
    id_work integer,
    create_date timestamp,
    materialnumber numeric(8, 2),
    is_complit boolean,
    fio varchar(255),
    d_date varchar(10),
    workitemsnotcomplit integer,
    workitemscomplit integer,
    full_name varchar(101),
    statusid smallint,
    statusname varchar(255),
    is_print boolean
)
language sql
stable
as $$
    with top_works as (
        select
            w.id_work,
            w.create_date,
            w.materialnumber,
            w.is_complit,
            w.fio,
            w.id_employee,
            w.statusid,
            w.print_date,
            w.sendtoclientdate,
            w.sendtodoctordate,
            w.sendtoorgdate,
            w.sendtofax
        from works w
        where w.is_del <> true
        order by w.id_work desc
        limit 3000
    ),
    work_ids as (
        select array_agg(tw.id_work) as ids
        from top_works tw
    ),
    workitem_counts as (
        select c.*
        from work_ids ids
        cross join f_workitems_count_by_id_work(ids.ids) c
    )
    select
        tw.id_work,
        tw.create_date,
        tw.materialnumber,
        tw.is_complit,
        tw.fio,

        to_char(tw.create_date, 'DD.MM.YYYY')::varchar(10) as d_date,

        coalesce(wic.workitemsnotcomplit, 0) as workitemsnotcomplit,
        coalesce(wic.workitemscomplit, 0) as workitemscomplit,

        f_employee_fullname(tw.id_employee) as full_name,

        tw.statusid,
        ws.statusname,

        (
            tw.print_date is not null
            or tw.sendtoclientdate is not null
            or tw.sendtodoctordate is not null
            or tw.sendtoorgdate is not null
            or tw.sendtofax is not null
        ) as is_print

    from top_works tw
    left join workitem_counts wic
        on wic.id_work = tw.id_work
    left join workstatus ws
        on ws.statusid = tw.statusid
    order by tw.id_work desc;
$$;

-- ============================================================
-- Проверочный запрос
-- ============================================================

-- select *
-- from f_works_list()
-- limit 3000;
